name: Generate SKU List

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-sku-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Update SKU Options
        run: |
          # Define the JSON data
          json_data='{
            "data": [
              {"id": 1, "name": "XDR-ESS", "updated_at": "2023-06-22T19:58:32.71252Z"},
              {"id": 2, "name": "XDR-ADV", "updated_at": "2023-06-22T19:58:32.71252Z"},
              {"id": 3, "name": "XDR-ING-1GB", "updated_at": "2023-06-22T19:58:32.71252Z"},
              {"id": 4, "name": "XDR-DATARET-90", "updated_at": "2023-06-22T19:58:32.71252Z"},
              {"id": 5, "name": "XDR-DATARET-180", "updated_at": "2023-06-22T19:58:32.71252Z"}
            ]
          }'

          # Extract SKU names using jq and construct a properly formatted output
          skus=$(echo "$json_data" | jq -r '.data[].name')
          output=""
          first=true
          for sku in $skus
          do
             if $first; then
               output+="- $sku\n"
               first=false
             else
               output+="          - $sku\n"  # Indent subsequent items
             fi
          done

          # Use printf to ensure proper formatting in the generated file
          printf -v formatted_output "%s" "$output"

          # Replace the placeholder in the workflow file
          sed -i "s|# This needs to be replaced with a proper list during runtime|$formatted_output|g" $GITHUB_WORKSPACE/.github/workflows/claim-code.yml

      - name: Set up Git for Bot User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit files with specific author
        run: |
          git add .github/workflows/claim-code.yml
          git commit --author="Bot Author <bot-author@example.com>" -m "Updated SKU options"
          git push origin main

    env:
      GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
